export const SET_ENVIRONMENT = 'SET_ENVIRONMENT';

export const RESET_STATE = 'RESET_STATE';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_START = 'RESET_START';
export const RESET_COMPLETED = 'RESET_COMPLETED';
export const RESET_POPUP = 'RESET_POPUP';
export const CHANGE_STATE = 'CHANGE_STATE';
export const CHANGE_MAIN_TAB = 'CHANGE_MAIN_TAB';

export const ATM_LOC_START_LOAD = 'ATM_LOC_START_LOAD';
export const ATM_LOC_FINISHED_LOAD = 'ATM_LOC_FINISHED_LOAD';

export const INFO_WINDOW_SHOW = 'INFO_WINDOW_SHOW';
export const INFO_WINDOW_HIDE = 'INFO_WINDOW_HIDE';
